services:
  postgres:
    image: postgres:17
    ports:
      - 5432:5432
    volumes:
      - ./.volumes/postgres/data:/var/lib/postgresql/data/
      - ./data/schemas.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=admin
      - POSTGRES_DB=ChronoVault