version: '3.8'

services:
    postgres-db:
        image: postgres:latest
        container_name: ChronoVault-db
        environment:
            POSTGRES_DB: ChronoVault
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
        restart: unless-stopped

volumes:
    pgdata:

